name: Clang Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-format-check:
    name: Clang Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang-format-20
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get update
          sudo apt-get install -y clang-format-20
          sudo ln -sf /usr/bin/clang-format-20 /usr/local/bin/clang-format

      - name: Make script executable
        run: chmod +x scripts/verify-formatting.sh

      - name: Run verify-formatting.sh
        run: ./scripts/verify-formatting.sh